version: 1

sources:
  - name: raw
    database: railway 
    schema: ecommerce_data
    tables:
      - name: olist_orders
      - name: olist_order_items
      - name: olist_order_payments
      - name: olist_customers
      - name: olist_sellers
      - name: olist_products
      - name: product_category_name_translation
      - name: olist_closed_deals
      - name: olist_marketing_qualified_leads_dataset
      - name: olist_geolocation
      - name: olist_order_reviews_dataset